### ISSUE TITLE
Trigger Updates

### ISSUE THREAD

**Issue by Rodriwp** [Rodriwp/RYS_UC3M#13]

**Comment by pabberper** [comment]
Casos que accionan el trigger de RIPv2

1 The router receives a specific request for an update.
2 Information from another interfaces has caused a modification to the RIP database causing an update to be triggered.
3 An interface goes up or down; in which case a partial database update is sent.
4 A router is powered on thus triggering an update of the FULL database.

1 y 4 hechos
2 y 3 son para multiinterfaz
